# Generated by Django 5.2.9 on 2025-12-14 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this contact message', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the person contacting', max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Email address for reply', max_length=254)),
                ('message', models.TextField(help_text='Message content', max_length=2000)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=255, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('REPLIED', 'Replied'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', help_text='Current processing status', max_length=20)),
                ('source', models.CharField(default='portfolio_site', help_text='Source of the contact (e.g., portfolio_site, landing_page)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the message was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the message was last updated')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_con_status_4b75ca_idx'), models.Index(fields=['email', '-created_at'], name='contact_con_email_4f8e99_idx')],
            },
        ),
    ]
